spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/algoarena
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: silbroeh@gmail.com
    password: chrh hewg obwh axmm
    auth-code-length: 10
    auth-code-expiration-millis: 300000
    properties:
      mail:
        smtp:
          address: admin@algo-arena.net
          personal: Algo Arena
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

  cache:
    type: redis

  profiles:
    active: dev

jwt:
  secret-key: algo-arena-token-secret-key-256-bit
  access-duration: 600000